/*
 * generated by Xtext 2.19.0
 */
package circus.robocalc.robosim.graphical.label.ide


/**
 * Use this class to register ide components.
 */
class RoboSimLabelIdeModule extends AbstractRoboSimLabelIdeModule {
}
