/*
 * generated by Xtext 2.19.0
 */
package circus.robocalc.robosim.graphical.label.tests

import circus.robocalc.robosim.graphical.label.roboSimLabel.LabelModel
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(RoboSimLabelInjectorProvider)
class RoboSimLabelParsingTest {
	@Inject
	ParseHelper<LabelModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			expression 1 + 1
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
